# Generated by Django 4.2 on 2023-04-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that phone already exists.'}, help_text='Обязательно поле для регистрации', max_length=150, unique=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
